name: push to server

on:
  push:
    branches: [ main ]

jobs:  
  release:
    name: build
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: "remote server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SSH }}
          username: ${{ secrets.USERNAME_SSH }}
          password: ${{ secrets.PASSWORD_SSH }}
          script: |
            cd /home/widi/stacks/segar-backend-api
            git pull origin main
            ./update.sh
            docker pull registry.gitlab.com/gitops-widi/container-registry/segarbox/laravel:php8.0-fpm
